### ISSUE TITLE
希望能说一下处理touch事件改为“onInterceptTouchEvent”函数的原因

### ISSUE THREAD

**Issue by TellH** [xiaolifan/NsRefreshLayout#2]
希望能说一下处理touch事件改为“onInterceptTouchEvent”函数的原因

**Comment by laomengzhu** [comment]
http://blog.csdn.net/laomengzhu/article/details/50619121

**Comment by TellH** [comment]
终于找到原文的出处了~~刚看到一篇转载不标明出处的“原创”文章，谢谢，我看看~

**Comment by insen-ok** [comment]
下拉或上拉时，加载动画有卡顿现象
